### ISSUE TITLE
[render-dot] Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

### ISSUE THREAD

**Issue by reregaga** [cancerberoSgx/univac#168]
@cancerberoSgx, I try to run a [simple example](https://github.com/cancerberoSgx/univac/tree/master/render-dot#javascript) and get an errors:
- `Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)`
- `Error: Cannot find module 'misc-utils-of-mine-typescript'`

I understand I need to install this [canvas](https://www.npmjs.com/package/canvas) library?

My code:
```js
import {renderDot} from 'render-dot'
const svgCode = await renderDot({
  input: 'digraph { a -> b; }'
})
console.log(svgCode)
```
Errors:
```
C:\Users\%USERNAME%\code>node tempfile.js
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\living\nodes\HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\living\generated\HTMLCanvasElement.js:41:47)
    at Function.supports (C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:8487:20)
    at C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:9391:45
    at Object.<anonymous> (C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:11138:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12) undefined
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\living\nodes\HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\living\generated\HTMLCanvasElement.js:41:47)
    at Function.supports (C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:8487:20)
    at C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:12808:46
    at Object.<anonymous> (C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:14922:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12) undefined
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\living\nodes\HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (C:\Users\%USERNAME%\code\node_modules\jsdom\lib\jsdom\living\generated\HTMLCanvasElement.js:41:47)
    at Function.supports (C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:8487:20)
    at C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:16963:46
    at Object.<anonymous> (C:\Users\%USERNAME%\code\node_modules\fabric\dist\fabric.js:17294:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12) undefined
node:internal/modules/cjs/loader:939
  const err = new Error(message);
              ^

Error: Cannot find module 'misc-utils-of-mine-typescript'
Require stack:
- C:\Users\%USERNAME%\code\node_modules\render-dot\dist\src\types.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\%USERNAME%\code\node_modules\render-dot\dist\src\types.js:3:39)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\%USERNAME%\\code\\node_modules\\render-dot\\dist\\src\\types.js'
  ]
}

Node.js v18.0.0
```

Node.js: v18
OS: Windows 10

**Comment by omundy** [comment]
Experiencing the same.

**Comment by cancerberoSgx** [comment]
Hello there, sorry I wasn't maintaining this project but I will take a look - probably those dev dependencies can be easily fixed, thanks for reporting

**Comment by syzer** [comment]
fixed here : #201 
@cancerberoSgx 
@omundy
